version: '3.7'

services:
  db:
    container_name: mysqldb
    image: bitnami/mysql:latest
    ports:
      - 3306:3306
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      # - MYSQL_USER=matheusdev
      # - MYSQL_PASSWORD=12345678A
      - MYSQL_DATABASE=agendamento_development
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - backend-network  

  web:
    stdin_open: true
    tty: true
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
        PORT: 3030
    volumes:
      - ./:/opt/app
    depends_on:
      db:
        condition: service_healthy 

    ports:
      - '3030:3030'
    environment:
      PORT: 3030
    healthcheck:
      test: curl --fail backend:3030/health || exit 1
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - backend-network

networks:
  backend-network:
    name: backend-network
    driver: bridge